# -*- coding: utf-8 -*-
"""men-women-deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ihiqkh5SfFcP8pdEKXwEPZA5Qh-Ya_u

# Deploy a Trained Model
"""

from tensorflow import keras
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

"""## 1- Load pre-trained model"""

from google.colab import drive
drive.mount('/content/drive')

!cp '/content/drive/MyDrive/fine_tuning.h5' '.'

model = keras.models.load_model("fine_tuning.h5")

"""## 2- Load Image(s)"""

# img1 = 'Fchollet.jpg'
# img2 = 'Fei-Fei_Li_at_AI_for_Good_2017.jpg'
img1 = keras.utils.get_file(origin="https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Fchollet.jpg/220px-Fchollet.jpg")
img2 = keras.utils.get_file(origin="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Fei-Fei_Li_at_AI_for_Good_2017.jpg/220px-Fei-Fei_Li_at_AI_for_Good_2017.jpg")
img1 = image.load_img(img1, target_size=(180, 180))
x1 = image.img_to_array(img1)
x1 = np.expand_dims(x1, axis=0)
img2 = image.load_img(img2, target_size=(180, 180))
x2 = image.img_to_array(img2)
x2 = np.expand_dims(x2, axis=0)

plt.imshow(img1)

plt.imshow(img2)

"""## 3- Predict Classes"""

pred1 = model.predict(x1)
pred2 = model.predict(x2)

print(pred1)
print(pred2)

plt.imshow(img1)
plt.axis('off')
plt.title('Man' if pred1<0.5 else 'Woman')
plt.show()

plt.imshow(img2)
plt.axis('off')
plt.title('Man' if pred2<0.5 else 'Woman')
plt.show()